# <a name="exceptions"></a><span data-ttu-id="292a3-101">Exceptions</span><span class="sxs-lookup"><span data-stu-id="292a3-101">Exceptions</span></span>

<span data-ttu-id="292a3-102">Les exceptions en c# fournissent une manière structurée, uniforme et de type sécurisé de niveau système et niveau de l’application de gestion des conditions d’erreur.</span><span class="sxs-lookup"><span data-stu-id="292a3-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="292a3-103">Le mécanisme d’exception en c# est très similaire à celui de C++, avec quelques différences importantes :</span><span class="sxs-lookup"><span data-stu-id="292a3-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="292a3-104">En c#, toutes les exceptions doivent être représentées par une instance d’un type de classe dérivé `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="292a3-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="292a3-105">En C++, n’importe quelle valeur de n’importe quel type peut être utilisé pour représenter une exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="292a3-106">En c#, un bloc finally ([l’instruction try](statements.md#the-try-statement)) peut être utilisé pour écrire du code d’arrêt qui s’exécute dans une exécution normale et des conditions exceptionnelles.</span><span class="sxs-lookup"><span data-stu-id="292a3-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="292a3-107">Ce code est difficile d’écrire en C++ sans duplication de code.</span><span class="sxs-lookup"><span data-stu-id="292a3-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="292a3-108">En c#, les exceptions au niveau du système telles que le dépassement de capacité, division par zéro et null déréférence ont bien définis des classes d’exception et à concorde avec les conditions d’erreur au niveau de l’application.</span><span class="sxs-lookup"><span data-stu-id="292a3-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="292a3-109">Causes des exceptions</span><span class="sxs-lookup"><span data-stu-id="292a3-109">Causes of exceptions</span></span>

<span data-ttu-id="292a3-110">Exception peut être levée de deux manières différentes.</span><span class="sxs-lookup"><span data-stu-id="292a3-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="292a3-111">Un `throw` instruction ([l’instruction throw](statements.md#the-throw-statement)) lève une exception immédiatement et sans condition.</span><span class="sxs-lookup"><span data-stu-id="292a3-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="292a3-112">Contrôle n’atteint jamais l’instruction qui suit immédiatement la `throw`.</span><span class="sxs-lookup"><span data-stu-id="292a3-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="292a3-113">Certaines des conditions exceptionnelles qui surviennent pendant le traitement d’instructions c# et expression provoquent une exception dans certaines circonstances, lorsque l’opération ne peut pas être terminée normalement.</span><span class="sxs-lookup"><span data-stu-id="292a3-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="292a3-114">Par exemple, une opération de division entier ([opérateur de Division](expressions.md#division-operator)) lève une `System.DivideByZeroException` si le dénominateur est égal à zéro.</span><span class="sxs-lookup"><span data-stu-id="292a3-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="292a3-115">Consultez [Classes d’exceptions courantes](exceptions.md#common-exception-classes) pour obtenir la liste des différentes exceptions qui peuvent se produire de cette façon.</span><span class="sxs-lookup"><span data-stu-id="292a3-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="292a3-116">La classe System.Exception</span><span class="sxs-lookup"><span data-stu-id="292a3-116">The System.Exception class</span></span>

<span data-ttu-id="292a3-117">Le `System.Exception` classe est le type de base de toutes les exceptions.</span><span class="sxs-lookup"><span data-stu-id="292a3-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="292a3-118">Cette classe possède quelques propriétés notables qui partagent toutes les exceptions :</span><span class="sxs-lookup"><span data-stu-id="292a3-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="292a3-119">`Message` est une propriété en lecture seule de type `string` qui contient une description explicite de la raison de l’exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="292a3-120">`InnerException` est une propriété en lecture seule de type `Exception`.</span><span class="sxs-lookup"><span data-stu-id="292a3-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="292a3-121">Si sa valeur est non null, il fait référence à l’exception qui a provoqué l’exception actuelle, autrement dit, l’exception actuelle a été levée dans un bloc catch gère les `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="292a3-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="292a3-122">Sinon, sa valeur est null, indiquant que cette exception n’a pas provoquée par une autre exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="292a3-123">Le nombre d’objets d’exception chaînés de cette manière peut être arbitraire.</span><span class="sxs-lookup"><span data-stu-id="292a3-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="292a3-124">La valeur de ces propriétés peut être spécifiée dans les appels au constructeur d’instance pour `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="292a3-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="292a3-125">Gestion des exceptions</span><span class="sxs-lookup"><span data-stu-id="292a3-125">How exceptions are handled</span></span>

<span data-ttu-id="292a3-126">Les exceptions sont gérées par un `try` instruction ([l’instruction try](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="292a3-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="292a3-127">Lorsqu’une exception se produit, le système recherche le plus proche `catch` clause qui peut gérer l’exception, comme déterminé par le type au moment de l’exécution de l’exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="292a3-128">Tout d’abord, la méthode actuelle est recherchée englobante lexicalement `try` instruction et les clauses catch associé de l’instruction try sont considérés comme dans l’ordre.</span><span class="sxs-lookup"><span data-stu-id="292a3-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="292a3-129">Si cette tentative échoue, la méthode qui a appelé la méthode actuelle est recherchée englobante lexicalement `try` instruction qui comprend le point de l’appel à la méthode actuelle.</span><span class="sxs-lookup"><span data-stu-id="292a3-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="292a3-130">Cette recherche se poursuit jusqu'à un `catch` clause est trouvée, qui peut gérer l’exception actuelle, en nommant une classe d’exception qui est de la même classe ou une classe de base du type d’exécution de l’exception levée.</span><span class="sxs-lookup"><span data-stu-id="292a3-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="292a3-131">Un `catch` clause qui ne nomme pas une classe d’exception peut gérer n’importe quelle exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="292a3-132">Une fois une clause catch correspondante est trouvée, le système se prépare à transférer le contrôle à la première instruction de la clause catch.</span><span class="sxs-lookup"><span data-stu-id="292a3-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="292a3-133">Avant le début de l’exécution de la clause catch, le système exécute d’abord, dans l’ordre, les `finally` clauses qui ont été associés à des instructions try plus imbriquées que celui qui a intercepté l’exception.</span><span class="sxs-lookup"><span data-stu-id="292a3-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="292a3-134">Si aucune clause catch correspondante n’est trouvée, deux choses se produit :</span><span class="sxs-lookup"><span data-stu-id="292a3-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="292a3-135">Si la recherche d’une clause catch correspondante atteint un constructeur statique ([constructeurs statiques](classes.md#static-constructors)) ou un initialiseur de champ statique, un `System.TypeInitializationException` est levée au point qui a déclenché l’appel du constructeur statique.</span><span class="sxs-lookup"><span data-stu-id="292a3-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="292a3-136">L’exception interne de la `System.TypeInitializationException` contient l’exception qui a été levée.</span><span class="sxs-lookup"><span data-stu-id="292a3-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="292a3-137">Si la recherche de clauses catch correspondantes atteint le code qui a initialement a démarré le thread, puis l’exécution du thread est interrompue.</span><span class="sxs-lookup"><span data-stu-id="292a3-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="292a3-138">L’impact d’un tel arrêt est défini par l’implémentation.</span><span class="sxs-lookup"><span data-stu-id="292a3-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="292a3-139">Les exceptions qui se produisent pendant l’exécution du destructeur méritent une mention spéciale.</span><span class="sxs-lookup"><span data-stu-id="292a3-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="292a3-140">Si une exception se produit pendant l’exécution du destructeur, cette exception n’est pas interceptée, l’exécution de ce destructeur est arrêtée, puis le destructeur de la classe de base (le cas échéant) est appelé.</span><span class="sxs-lookup"><span data-stu-id="292a3-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="292a3-141">S’il n’existe aucune classe de base (comme dans le cas de la `object` type) ou si il n’existe aucun destructeur de classe de base, l’exception est ignorée.</span><span class="sxs-lookup"><span data-stu-id="292a3-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="292a3-142">Classes d’exceptions courantes</span><span class="sxs-lookup"><span data-stu-id="292a3-142">Common Exception Classes</span></span>

<span data-ttu-id="292a3-143">Les exceptions suivantes sont levées par certaines opérations c#.</span><span class="sxs-lookup"><span data-stu-id="292a3-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="292a3-144">Classe de base pour les exceptions qui se produisent pendant des opérations arithmétiques, telles que `System.DivideByZeroException` et `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="292a3-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="292a3-145">Levée lorsqu’un stockage dans un tableau échoue, car le type réel de l’élément stocké est incompatible avec le type réel du tableau.</span><span class="sxs-lookup"><span data-stu-id="292a3-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="292a3-146">Levée lorsqu’une tentative de division d’une valeur intégrale par zéro se produit.</span><span class="sxs-lookup"><span data-stu-id="292a3-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="292a3-147">Levée lorsqu’une tentative d’indexation d’un tableau via un index qui est inférieur à zéro ou en dehors des limites du tableau.</span><span class="sxs-lookup"><span data-stu-id="292a3-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="292a3-148">Levée lorsqu’une conversion explicite d’un type de base ou l’interface en un type dérivé échoue au moment de l’exécution.</span><span class="sxs-lookup"><span data-stu-id="292a3-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="292a3-149">Levée quand un `null` référence est utilisée dans une manière qui rend obligatoire l’objet référencé.</span><span class="sxs-lookup"><span data-stu-id="292a3-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="292a3-150">Levée lorsqu’une tentative d’allocation de mémoire (via `new`) échoue.</span><span class="sxs-lookup"><span data-stu-id="292a3-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="292a3-151">Levée quand une opération dans un contexte `checked` engendre un dépassement.</span><span class="sxs-lookup"><span data-stu-id="292a3-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="292a3-152">Levée lorsque la pile d’exécution est épuisée par un trop grand nombre des appels de méthode en attente ; en général, le signe d’une récurrence très profonde ou non liée.</span><span class="sxs-lookup"><span data-stu-id="292a3-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="292a3-153">Levée lorsqu’un constructeur statique lève une exception et non `catch` clauses existe pour l’intercepter.</span><span class="sxs-lookup"><span data-stu-id="292a3-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
